version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres 
    ports:
      - 5432:5432

  trino:
    image: trinodb/trino
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./trino/etc:/etc/trino

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

networks:
  shared_network:
    driver: bridge
